<?php

declare(strict_types=1);

namespace Tarfinlabs\EventMachine\Models;

use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Tarfinlabs\EventMachine\EventCollection;
use Tarfinlabs\EventMachine\Enums\SourceType;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Tarfinlabs\EventMachine\Services\ArchiveService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Tarfinlabs\EventMachine\Database\Factories\MachineEventFactory;

/**
 * Class MachineEvent.
 *
 * The MachineEvent model represents an event generated by a machine.
 *
 * @property string $id The unique identifier of the event.
 * @property int $sequence_number The sequence number of the event.
 * @property Carbon $created_at The timestamp when the event was created.
 * @property SourceType $source The source type of the event (Internal or External).
 * @property string $type The type of the event.
 * @property array<string, mixed> $payload The payload data of the event.
 * @property int $version The version of the event.
 * @property string $machine_id The unique identifier of the machine that generated the event.
 * @property array<int, string> $machine_value Machine state after the event.
 * @property string $root_event_id The unique identifier of the root event in event sequence.
 * @property array<string, mixed> $context The context data of the event.
 * @property array<string, mixed> $meta The metadata of the event.
 */
class MachineEvent extends Model
{
    /** @use HasFactory<MachineEventFactory> */
    use HasFactory;

    use HasUlids;

    public $timestamps = false;

    /**
     * Boot the model and register event listeners.
     */
    protected static function booted(): void
    {
        static::creating(function (MachineEvent $event): void {
            // Auto-restore: if archive exists for this root_event_id, restore and delete it
            // Uses restoreAndDelete() which has row-level locking to prevent race conditions
            $rootEventId = $event->root_event_id ?? '';
            if ($rootEventId !== '') {
                (new ArchiveService())->restoreAndDelete($rootEventId);
            }
        });
    }

    protected $fillable = [
        // ID Related Attributes
        'id',
        'sequence_number',
        'created_at',
        // Machine ID Related Attributes
        'machine_id',
        'machine_value',
        'root_event_id',
        // Event Related Attributes
        'source',
        'type',
        'payload',
        'version',
        // Machine Data Related Attributes
        'context',
        'meta',
    ];
    protected $casts = [
        'id'              => 'string',
        'sequence_number' => 'integer',
        'created_at'      => 'datetime',
        'machine_id'      => 'string',
        'machine_value'   => 'array',
        'root_event_id'   => 'string',
        'source'          => SourceType::class,
        'type'            => 'string',
        'payload'         => 'array',
        'version'         => 'integer',
        'context'         => 'array',
        'meta'            => 'array',
    ];

    /**
     * Create a new instance of MachineEventFactory.
     */
    protected static function newFactory(): MachineEventFactory
    {
        return MachineEventFactory::new();
    }

    /**
     * Create a new collection of models.
     *
     * This method overrides the default Eloquent collection with a custom
     * EventCollection. This allows for additional methods to be available
     * on the collection of MachineEvent models.
     *
     * @param  array<int, MachineEvent>  $models  An array of MachineEvent models.
     *
     * @return EventCollection A new instance of EventCollection.
     */
    public function newCollection(array $models = []): EventCollection
    {
        return new EventCollection($models);
    }
}
