name: Pest-Types

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pest-types:
    name: pest-types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Execute tests
        run: vendor/bin/pest --type-coverage --min=100 --colors=always
